services:
  app:
    build:
      context: .
    container_name: freebie
    restart: always
    environment:
      - TZ=Africa/Cairo
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_USERNAME=username
      - REDIS_PASSWORD=authpassword
      - PORT=5000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/freebie?schema=public
    ports: 
      - "5000:5000"
    depends_on:
      - db
      - redis
    develop:
      watch:
        - action: sync+restart
          path: ./*
          target: /docker      
    volumes:
      - .:/docker
  redis:
    image: redis:7.2
    command: redis-server --requirepass authpassword --user username
    container_name: redis-server
    environment:
      - TZ=Africa/Cairo
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  worker:
    build:
      context: .
    container_name: freebie-worker
    restart: always
    environment:
      - TZ=Africa/Cairo
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/freebie?schema=public
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=authpassword
      - NODE_ENV=development
    depends_on:
      - redis
      - db
    command: node helpers/cron/execute-job-in-bullmq.js  --watch
    develop:
      watch:
        - action: sync+restart
          path: ./*
          target: /docker      
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - TZ=Africa/Cairo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freebie
    ports:
      - "5439:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres-data: