services:
  app:
    build:
      context: .
    container_name: freebie
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/freebie?schema=public
    ports: 
      - "5000:5000"
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: ./*
          target: /docker

    volumes:
      - .:/docker
  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freebie
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: